### ISSUE TITLE
谷歌翻译死了（大陆地区）

### ISSUE THREAD

**Issue by goodfish-jhy** [wly2014/TranslationToolbox#11]
# 谷歌翻译死了（大陆地区）

就在昨天，谷歌宣布：
> 9月末，谷歌旗下网页翻译工具谷歌翻译停止了中国区服务，现在访问translate.google.cn网页会指向谷歌香港站。
> 此做法与此前谷歌搜索、谷歌地图等功能退出中国大陆时一致。目前谷歌在国内仍然提供部分可被访问的功能，包括谷歌广告、开发者社区、Android开发者社区等，主要为开发者和客户提供支援。
> 早在2010年谷歌宣布退出中国之后，仅仅保留了谷歌翻译和谷歌地图两款服务。2020年2月3日起，谷歌地图在国内停止服务

希望可以添加修改翻译引擎的功能

**Comment by wly2014** [comment]
已更新了有道翻译的API（V0.4.1），后续有时间继续更新百度翻译的API，放弃修复google翻译的API了

**Comment by goodfish-jhy** [comment]
行吧，尽快，毕竟这么好的项目不多了
