### ISSUE TITLE
有道API失效，没有翻译结果。。。

### ISSUE THREAD

**Issue by xiaoqf96** [wly2014/TranslationToolbox#2]
您的请求来源非法，商业用途使用请关注有道翻译API官方网站“有道智云”: http://ai.youdao.com

**Comment by xiaoqf96** [comment]
【已解决】win10禁用后再次启用谷歌，必应，还有百度都能用，很nice。
希望能自定义默认翻译api；

**Comment by wly2014** [comment]
首先感谢您对TranslationToolbox的支持。
因为当前并没有采用有道翻译的官方api，所以可能在调用次数上有些限制，造成了这个问题。

**Comment by keyTyping** [comment]
重载试了, 还是不行, 找到另一个方法:
1,在电脑的user文件夹里找到 .vscode文件夹, 在这个文件夹里面找到 translationToolbox文件夹
2,打开Extension.js文件
3,找到function hover2translate()里面 词和短语翻译的一部分, 默认用的是有道翻译的函数, 改成你想要的其他函数名, 保存, 重新打开vscode 就可以了

**Comment by wly2014** [comment]
已经更新了软件，欢迎升级
