### ISSUE TITLE
项目是不是不维护了?翻译API拿不到数据了

### ISSUE THREAD

**Issue by Zhangxxl** [wly2014/TranslationToolbox#3]

**Comment by markjoin123** [comment]
拿不到数据

**Comment by NU-LL** [comment]
+1 刚刚一直认为是自己操作有问题。。。

**Comment by wenlisu** [comment]
+1 一样的问题，求解决

**Comment by wenlisu** [comment]
看了下百度翻译api，要收费了。
![image](https://user-images.githubusercontent.com/16130875/53154793-7f91cf80-35f6-11e9-8bac-f1632b34a794.png)

**Comment by wly2014** [comment]
已经修复了百度翻译的接口问题。
感谢使用和支持。
