### ISSUE TITLE
翻译失败或是找不到对应的翻译后,显示的是上一个单词的翻译结果

### ISSUE THREAD

**Issue by chinayangxiaowei** [wly2014/TranslationToolbox#4]

**Comment by Flcwl** [comment]
是的，翻译反应有点慢，划词显示上一个单词结果。

正常来讲双击即选中。但是鼠标需要移出（鼠标单词此外），再移进（鼠标到单词上）才能显示结果。
这里希望可以优化。

**Comment by YLQZ** [comment]
这个确实是个大问题哎，再次移入还显示上一个的翻译，这不大好啊，你的逻辑过程应该重新规划一下了，移入取词的时候要清掉上一次的翻译结果，并且做一个小的翻译缓存池 如果翻译过的就不要重复翻译，直接从翻译缓存池里拿就行了，翻译缓存池设定一个上限值，不然占用太大没啥用
